# Generated by Django 5.1.1 on 2025-10-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_projects'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timeentry',
            new_name='tracker_tim_employe_7c70eb_idx',
            old_name='tracker_tim_employe_1e4cdb_idx',
        ),
    ]
