# Generated by Django 5.1.1 on 2025-10-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_finance'),
        ('tracker', '0003_rename_tracker_tim_employe_1e4cdb_idx_tracker_tim_employe_7c70eb_idx'),
    ]

    operations = [
    ]
