# Generated by Django 5.1.1 on 2025-10-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_employee_profile_fields'),
        ('tracker', '0004_merge_20251001_2019'),
    ]

    operations = [
    ]
